### ISSUE TITLE
@devcontainer/cli@0.9.1 unable to run devcontainer up

### ISSUE THREAD

**Issue by doggy8088** [devcontainers/cli#108]
I'm using Windows 10. I've just checked [Development container CLI][1] page and installed dev container CLI using the following command:

    npm install -g @devcontainers/cli

After been installed, I realized that it's a bit different than docs said:

I only have two commands:

    devcontainer <command>
    
    Commands:
      devcontainer open [path]   Open a dev container in VS Code
      devcontainer build [path]  Build a dev container image
    
    Options:
      -h, --help               Show help  [boolean]
          --disable-telemetry  Disable telemetry  [boolean] [default: false]

What am I missing?

  [1]: https://code.visualstudio.com/docs/remote/devcontainer-cli

**Comment by bamurtaugh** [comment]
Thanks for filing! It looks like you may have the previous VS Code dev container CLI installed as well. 

Could you run `devcontainer which` to see if it outputs the path where you installed the package from `devcontainers/cli`, or if it outputs a path to the older CLI?

**Comment by doggy8088** [comment]
I found the exact problem now.  Here is how I can reproduce this problem:

1. Execute `Remote-Containers: Install devcontainer CLI` in VSCode.

    ![image](https://user-images.githubusercontent.com/88981/183672033-532e5c56-ee5d-4ba9-b499-c772e65dd4ac.png)

2. I found that this VSCode command will add the following path to `PATH` environment.

    ```txt
    c:\Users\user\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\cli-bin
    ```

3. Run the `devcontainer.cmd` from this folder will lead to this problem.

    ![image](https://user-images.githubusercontent.com/88981/183672756-1b3b19b3-d56b-4841-9b58-a6c36e1364ff.png)

I think you should prevent this dependency issue from the `Remote-Containers` extension.

**Comment by chrmarti** [comment]
The latest version of Remote-Containers forwards to the @devcontainers/cli. Closing as fixed.
