### ISSUE TITLE
Local feature not working in Remote-Containers

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/cli#116]
Remote-Containers 0.244.0

Using:
```json
{
	"context": ".",
	"dockerFile": "Dockerfile",
	"features": {
		"./local-features/foo": "latest"
	}
}
```

fails with:
```
ENOENT: no such file or directory, lstat '/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.244.0/local-features/foo'
```

**Comment by rzhao271** [comment]
On Windows, I get the error "Expected feature identifier to contain only alphanumeric and/or the '-' characters."
I'm also unable to build the container with that configuration.

**Comment by chrmarti** [comment]
Thanks @rzhao271, the following verifies the fix:

File layout:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/9205389/187997855-f6c9d1fa-df83-4dbf-9efc-6c22aeb0564a.png">

devcontainer.json:
```json
{
	"image": "ubuntu:latest",
	"features": {
		"./foo": "latest"
	}
}
```

devcontainer-feature.json:
```json
{
    "id": "foo"
}
```

install.sh:
```sh
#!/bin/sh

echo HERE!
echo THERE! >/there.txt
```

In the devcontainer check that the file `/there.txt` exists.

(If you want to reproduce the problem in 0.244.0 first, you need to change the feature's path in the devcontainer.json to `"./.devcontainer/foo"`. This changed later to be relative to the devcontainer.json.)

**Comment by rzhao271** [comment]
Verified in macOS on 0.252.0.
