### ISSUE TITLE
Add an option to show the version of the CLI

### ISSUE THREAD

**Issue by tschaffter** [devcontainers/cli#145]
I wanted to report the version of the CLI installed in my environment in another ticket, then realized that the option `--version` is not implemented.

```console
$ devcontainer --version
Specify a command
devcontainer <command>

Commands:
  devcontainer open [path]   Open a dev container in VS Code
  devcontainer build [path]  Build a dev container image

Options:
  -h, --help               Show help  [boolean]
      --disable-telemetry  Disable telemetry  [boolean] [default: false]
```

**Comment by joshspicer** [comment]
It appears you have the older 'vscode devcontainer CLI' installed on your machine.  Despite the name it is not the same as the source code in this repo.

I suggest removing that command and installing the CLI from this repository.  You can do so with npm:

```
npm install -g @devcontainers/cli
``` 

We're aware that two tools with the same name is confusing.  I imagine the goal is to either remove the "vscode devcontainer CLI" completely, or forward commands to a vscode-specific build of the OSS CLI (this repo).

@bamurtaugh @chrmarti @Chuxel - We should do something about this to avoid future confusion :)

**Comment by bamurtaugh** [comment]
Thanks for the tag @joshspicer and for opening this issue @tschaffter!

@alexdima and @chrmarti have been [working on](https://github.com/microsoft/vscode-remote-release/issues/7033) forwarding from the previous devcontainer CLI to the new OSS devcontainer CLI.

The built-in CLI `devcontainer` (or `devcontainer-insiders` for VS Code Insiders) of the Remote-Containers extension now forwards to the built-in open source CLI. The `open` command and the previous CLI arguments for the `build` command are also supported.

@chrmarti @alexdima is there another scenario we'll still need to cover where users may install / use the older CLI in another way (not from Remote-Containers)?

**Comment by chrmarti** [comment]
There is a `--version` option now, but I need to fix where it looks up the version (currently goes to the extension's package.json, but we want the CLI's package.json to be used).
