### ISSUE TITLE
`devcontainer build` lacks the `--cache-to` option of `docker buildx build`

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/cli#156]
Currently, the build command has the `--cache-from` option but not the `--cache-to` option.

My understanding is that the `--cache-from` option assumes that there is an image created by `--cache-to=type=inline`, etc. in the first place, so I was wondering why only one of them was implemented.
When building and pushing devcontainer from another machine with the same command, it may be useful to be able to use the cache.

**Comment by chrmarti** [comment]
We are always adding `--build-arg BUILDKIT_INLINE_CACHE=1`, so the image has all the metadata.

You might also be interested in the GitHub action to build the image and push it to a registry: https://github.com/devcontainers/ci

**Comment by eitsupi** [comment]
> We are always adding `--build-arg BUILDKIT_INLINE_CACHE=1`, so the image has all the metadata.

Oh, sorry. That makes sense.
I figured the cache wasn't working when I tried the build, but I must have misunderstood something!
