### ISSUE TITLE
`--label` option for `devcontainer build`

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/cli#157]
Maybe related to devcontainers/spec#18

Currently the only way to set labels seems to be to write to Dockerfiles or compose files, but if we store images in the registry, we may want to annotate the labels.
https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Comment by danielloader** [comment]
This has come up for me today, glad to see a tracking issue, shame it's not been looked at yet.

**Comment by samruddhikhandale** [comment]
Looks like this feature request slipped through the gaps, however we saw the latest https://github.com/devcontainers/cli/issues/837

Have https://github.com/devcontainers/cli/pull/846 open which attempts to support `--label`
