### ISSUE TITLE
Feature Dependencies - installsAfter not respected

### ISSUE THREAD

**Issue by virtualstaticvoid** [devcontainers/cli#163]
Hello,

I've written a couple of features for a project I'm working on and I've ran into situations where I'm not sure what the best approach to take is.

For example, I have a feature which involves installing a CLI tool using `npm`. Now, I'm not sure whether this feature should also install Node.js so that it is able to install the CLI tool, since I have no control over the base image, nor the included features in the `devcontainer.json` file.

The power of features, as I understand, is that they can be composed together; making each serve one purpose (installing the given feature) thus providing a simple way to handle all the tooling permutations for many different developers and/or teams whilst avoiding "golden container images"; and similar perhaps in concept to [buildpacks](https://buildpacks.io/).

So it occurred to me that since [`devcontainers/features`](https://github.com/devcontainers/features) already provide features for installing Node.js (and other language runtimes), it would be beneficial to make _my feature_ dependant on the `node` feature. Then I wouldn't need to worry about which base image a developer is using, and the `node` feature would be automatically included before mine, so my feature would install reliably.

Additional scenarios include:

* a Ruby gem which needs to build a native extension and thus requires `build-essential` to be installed.
* a Python package, installed via `pip`, needing to ensure Python and pip are installed.
* a Go CLI tool, which doesn't have a binary distribution, installed using `go install`, needing `go` to be installed.
* a `tflint` ruleset for AWS, which requires Terraform and `tflint` to be installed.

I realise installing packages using a `postCreateCommand` script can work, but it places the onus on the developer to know what features to include to install the given package. For example, I'm building features which install Python packages (e.g. `mkdocs`) for C# .Net developers, who wouldn't know to include the `python` feature.

I imagine a `devcontainer-feature.json` file including a `dependsOn` property, in the same schema as the `devcontainer.json` [`features` object](https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#devcontainerjson-properties).

I.e.

```json
"dependsOn": {
  "ghcr.io/user/repo/go": {},
  "ghcr.io/user/repo1/go:1": {},
  "ghcr.io/user/repo2/go:latest": {},
  "https://github.com/user/repo/releases/devcontainer-feature-go.tgz": { 
        "optionA": "value" 
  },
  "./myGoFeature": { 
        "optionA": true,
        "optionB": "hello",
        "version" : "1.0.0"
  }
}
```

**Comment by Chuxel** [comment]
Transferred issue to CLI repo since this is a bug verses a spec change at the moment.

**Comment by virtualstaticvoid** [comment]
Hello,

I tried running using the latest (HEAD) version and found that `installsAfter` still doesn't work.

I've created a test feature project, [`virtualstaticvoid/devcontainers-cli-issue-163`](https://github.com/virtualstaticvoid/devcontainers-cli-issue-163) to replicate the issue.

It has a feature which installs a Python package using `pip` and specifies `python` in the feature's `installsAfter`.

The test feature's `install.sh` script fails, since `pip` is not installed, and the output shows that the `python` feature doesn't get installed.

Please take a look to see whether I'm doing something wrong, or whether if my understanding of `installsAfter` is incorrect.

Thanks.

**Comment by Chuxel** [comment]
@edgonmsft ?

**Comment by edgonmsft** [comment]
Hi @virtualstaticvoid

I just recently fixed an issue with the implementation of `installsAfter` but I think you might be running into a different situation. The current definition for `installsAfter` is that it just reorders the installation of the features defined on `devcontainer.json` but doesn't add them to the list. 

Was that your understanding?

**Comment by virtualstaticvoid** [comment]
Hi @edgonmsft 

Ah ha! Yes, I assumed they would be added to the list automatically. 

I suppose having the feature dependencies automagically added presents many more challenges, so I understand now why it's implemented as a soft dependency instead.

I've updated my example feature's test to use a [`scenarios.json`](https://github.com/virtualstaticvoid/devcontainers-cli-issue-163/pull/1/files#diff-777117fc6a803427a32586d0cd1e924c5ade110749023175e8710d98765cd3fe) to work around the "default test" scenario which of course won't work. 

I have one scenario to include the `python` feature, but `devcontainer features test ...` fails as can be [seen in the test output](https://github.com/virtualstaticvoid/devcontainers-cli-issue-163/actions/runs/3055164386/jobs/4927913583) as it isn't installing the `python` feature as part of the test.

**Comment by virtualstaticvoid** [comment]
^^ For the test changes [see PR #1](https://github.com/virtualstaticvoid/devcontainers-cli-issue-163/pull/1/files)

**Comment by edgonmsft** [comment]
I think for this one the name in `installsAfter` has to be fully qualified. But let me make a test.

**Comment by Chuxel** [comment]
@edgonmsft Did we come to a conclusion on this one?

**Comment by edgonmsft** [comment]
Hi! Sorry for the delay responding here.
I tested the repository and found a couple of things:
- We only take into account the `scenarios.json` for global tests. those have to be under a `_global` folder inside `test`. The `default.sh` file also goes there.
- For `installsAfter` to be respected it has to be a fully qualified reference, for your case an example could be: `ghcr.io/devcontainers/features/python`
- Even after this two changes I still find a bug that needs fixing which is that the current scenarios only test features inside the repo, they don't take into account bringing features from OCR.

cc @joshspicer, @Chuxel, @samruddhikhandale, @chrmarti, @alexdima on your opinions on the best way forward for this scenario.

**Comment by Chuxel** [comment]
Ok - so:

1. There's clearly a bug with the test command here we should fix since I can see people wanting to be able to do this. There are some other gaps like being able to use `remoteUser`.
2. ...and some missing docs on what is / is not expected to work.
3. We should probably raise a spec issue on the idea of a "composite" feature that can automatically pull in the dependency rather than affecting order if it is referenced.

**Comment by edgonmsft** [comment]
Hey @virtualstaticvoid just to let you know that @joshspicer just merged a change that should support your scenario.

**Comment by joshspicer** [comment]
To @Chuxel 's (2) above, working on documentation for this command :) Feel free to provide input if you'd like:

https://github.com/devcontainers/cli/pull/219

**Comment by edgonmsft** [comment]
Awesome! Keep the feedback coming!

**Comment by rzhao271** [comment]
As part of [endgame](https://github.com/microsoft/vscode/issues/164400), I tried running through the readme in https://github.com/virtualstaticvoid/devcontainers-cli-issue-163, but I encountered the following issue when trying to run the tests inside of the devcontainer:

```
devcontainer features test . \
  --base-image mcr.microsoft.com/devcontainers/base:ubuntu-22.04 \
  --global-scenarios-only

┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
|    dev container 'features' |   
│           v0.22.0           │
└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘


📊 Scenarios:         /workspaces/devcontainers-cli-issue-163/test/_global

>  Running scenario:  pip-test
>  workspaceFolder:   /tmp/devcontainercli/container-features-test/1666898460355

⏳ Building test container...

[0 ms] @devcontainers/cli 0.22.0. Node.js v19.0.0. linux 5.10.102.1-microsoft-standard-WSL2 x64.
[-] Failed to launch container:

Command failed: docker ps -q -a --filter label=devcontainer.local_folder=/tmp/devcontainercli/container-features-test/1666898460355
```

**Comment by virtualstaticvoid** [comment]
Hi @rzhao271

Only running global scenarios worked, as can be seen in the automated tests in the repository. 

I had to explicitly remove running individual feature test, which explains the error you are getting.

**Comment by rzhao271** [comment]
It could just be my setup.
I'll mark the issue as verified based on https://github.com/devcontainers/cli/issues/163#issuecomment-1275988465. 
If the fix regresses, don't hesitate to comment on this issue or file a new one.
