### ISSUE TITLE
`devcontainer open` and `devcontainer --version` commands stuck

### ISSUE THREAD

**Issue by sampeson** [devcontainers/cli#175]
I have vscode remote-container extension installed and when I try to open devcontainer repository from command line (windows terminal, ubuntu 20.04) it gets stuck. I don't have node or npm installed in Ubuntu. It just prints the version info and after that nothing happens.

`$ devcontainer open codename/
[1667 ms] remote-containers 0.251.0.
`
I have installed devcontainer by using the "Remote-Containers: Install devcontainer CLI" method. Versions that I tried not working are v0.251.0 and pre-release v0.252.0. 

Workaround: after downgrading to v0.247.0 I'm able to start devcontainer from command line. "--version" argument is not available but I guess it was introduced in 0.251.

**Comment by joshspicer** [comment]
This repository is home to the https://www.npmjs.com/package/@devcontainers/cli, which is new and supersedes the CLI that is bundled with remote-containers.  I suggest installing the CLI directly from npm with `npm install -g @devcontainers/cli`
