### ISSUE TITLE
Incorrect value of 'remoteUser' cannot be fixed

### ISSUE THREAD

**Issue by olegkhar** [devcontainers/cli#194]
Repro state:
1. Create a sample project with 'devcontainer.json' in it
2. Modify 'devcontainer.json' to include:
`"remoteUser": "helloRoot"`
3. Run 'npx devcontainer up ...', to see an expected error message: "Shell server terminated unable to find user helloRoot"
4. Modify 'devcontainer.json' and fix the spelling of the remote user:
`"remoteUser": "root"`
5. Run 'npx devcontainer up' again.

This command will not succeed -- even though 'devcontainer.json' file was fixed.

**Comment by chrmarti** [comment]
We new read the configuration from the container's metadata.

**Comment by Chuxel** [comment]
@chrmarti I assume if someone rebuilt, this would then work?

**Comment by chrmarti** [comment]
Indeed, that might not be related to the metadata change. Could you try running `up` with `--remove-existing-container`?

**Comment by Chuxel** [comment]
@chrmarti Does https://github.com/devcontainers/cli/pull/254 (issue https://github.com/devcontainers/cli/pull/252) solve this problem? Seems like the same set of behaviors.

**Comment by olegkhar** [comment]
Yes, I've tried with version 0.23.1, and the problem is now fixed.  Many thanks!
