### ISSUE TITLE
`devcontainer features test` treats missing scenario script as ok

### ISSUE THREAD

**Issue by AlexanderLanin** [devcontainers/cli#213]
# Observation
When scenarios.json contains a scenario which does not have a shell script, it's treated as an "info".
There is no error, nothing is red, etc.

# Expectation
In my humble opinion this is fundamentally wrong.
Obviously I intended to execute a specific scenario, but forgot to include the script.
Please treat missing .sh file as test error.

**Comment by joshspicer** [comment]
I actually ran into this today.  I agree
