### ISSUE TITLE
`scenarios.json` does not support running with existing features

### ISSUE THREAD

**Issue by AlexanderLanin** [devcontainers/cli#217]
# Observation
When `ghcr.io/devcontainers/features/python:1` is added as a feature to scenarios.json, it attempts to read local file `path: '/workspaces/my-feature/src/ghcr.io/devcontainers/features/python:1'`.

# Expectation
It will use python feature for testing. Therefore I would see that it behaves correctly regarding `installsAfter` and my stuff can indeed use python.

# Background:
`my-feature` requires python 3.7, therefore I implemented a version detection in case the available version is too old. However as there is a python feature already, I don't want to add too much complex logic to my script. I have an error message which tells people to use https://github.com/devcontainers/features/tree/main/src/python in addition to `my-feature`.
However I cannot verify that this would indeed work!

**Comment by joshspicer** [comment]
Yes, this was also raised in https://github.com/devcontainers/cli/issues/217 and is good to point out. The command currently injects the appropriate relative path in for all Features in the scenario, so this is not expected to work (But I agree would be very handy!)
