### ISSUE TITLE
[Feature Request] `devcontainer templates apply` auto apply the default option values

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/cli#238]
At the moment it seems that if I do not specify the `-a` option with json when executing the `devcontainer templates apply` command, the options of the devcontainer-template.json will be empty.
It would be useful if default values were automatically set even in the absence of the `-a` option.

**Comment by joshspicer** [comment]
Agreed! I put up a PR yesterday to add in this functionality.  It does not require an additional flag, but rather will prefer user-provided options, and fall back to default if none is provided
https://github.com/devcontainers/cli/pull/235
