### ISSUE TITLE
exec /bin/bash is not interactive

### ISSUE THREAD

**Issue by jbcpollak** [devcontainers/cli#246]
When I build my container and then exec /bin/bash I get a command prompt within the container, but executing commands does nothing and I need to press Ctrl-C to escape:

```
>devcontainer exec --workspace-folder . /bin/bash
user@docker-desktop:~/src/$ ls
^C

````

**Comment by chrmarti** [comment]
Tracked as https://github.com/devcontainers/cli/issues/59. Thanks.
