### ISSUE TITLE
Can not change working directory ? (non root users home dir?)

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/cli#266]
Hello, I have noticed that my `ghcr.io/rocker-org/devcontainer-features/r-rig:1.0.1` installation is now failing, whereas it was working fine until 3 days ago.
Apparently it fails if there is a non-root user present.

The error occurs on this line.
https://github.com/rocker-org/devcontainer-features/blob/cbee3bfdce891012e88ae87c0da2c925a6a11301/src/r-rig/install.sh#L313

https://github.com/rocker-org/devcontainer-features/actions/runs/3386990635/jobs/5627128314#step:4:712
https://github.com/rocker-org/devcontainer-images/actions/runs/3386953191/jobs/5627039537#step:7:2193

Three days ago it was all green.
https://github.com/rocker-org/devcontainer-images/actions/runs/3361399450

Have there been any changes in behavior over the past few days?

**Comment by joshspicer** [comment]
This isn't exclusive failing with the `test` command, but also when trying to build within a dev container?

**Comment by eitsupi** [comment]
This will fail with an actual build, not a test command.
This command will not fail in a (old) pre-built container.

Perhaps by this change #263?

**Comment by joshspicer** [comment]
@chrmarti - Could this be related to the new permissions normalization? https://github.com/devcontainers/cli/pull/263/commits/2ade7e35e231a1dff42b485cb6cb53b1de4fd80e

**Comment by eitsupi** [comment]
OK, I got around this by moving to another temporary directory during installation rocker-org/devcontainer-features#95.
Thanks again for the continued development!

**Comment by joshspicer** [comment]
Thanks for raising! We definitely don't want to introduce changes that break existing Features, so this is an interesting case 🤔
