### ISSUE TITLE
[SECURITY] Should not run initializeCommand by default

### ISSUE THREAD

**Issue by kytans** [devcontainers/cli#290]
By default, devcontainers-cli will run whatever is specified as initializeCommand on the host.

This means any devcontainer can trivially take full control of the host OS, which is obviously highly undesirable since one of the main use cases for devcontainers is to be able to clone random projects from GitHub and do development on them securely even if the projects are malicious.

Instead, initializeCommand should only be run if a specific command-line argument is provided.

**Comment by chrmarti** [comment]
Closing per the above comment.

**Comment by alcuadrado** [comment]
> You have to first check if you want to trust the dev container's sources before you use it. There are several ways a dev container can access the host OS, not only initializeCommand.

Hey @chrmarti, where can I learn more about the other ways?
