### ISSUE TITLE
Hidden files excluded from devcontainer Docker build context

### ISSUE THREAD

**Issue by Rabadash8820** [devcontainers/cli#31]
# Repro steps

1. Create a VS Code workspace and add development container configuration files (exact features don't matter).
2. Add a hidden file to the `.devcontainer` folder (any file whose name starts with `.`)
3. Add this command to the Dockerfile:
    ```Dockerfile
    COPY . /tmp/buildcontext
    ```
4. Rebuild the devcontainer and open the workspace in it.
5. In the Terminal, run `ls /tmp/buildcontext`

# Expected behavior

Upon copying the entire `.devcontainer` folder into my devcontainer, I would see all of its files under `/tmp/buildcontext` within the container.

# Actual behavior

All files are copied to `/tmp/buildcontext` in the devcontainer _except_ hidden files.

# Notes

For context, I am working with the CDK (Cloud Development Kit) to provision AWS resources via code. One powerful feature of the CDK is that I can set [context](https://docs.aws.amazon.com/cdk/v2/guide/context.html) variables (config values, essentially) in a number of places, including the `~/.cdk.json` file. By adding context variables to that file, the values will be kept secret from version control, much like user secrets in Visual Studio. The project that I'm working on is using a devcontainer, so I was planning to add a "template" `.cdk.json` file in my `.devcontainer` folder with placeholder values, `COPY` it into my devcontainer from the Dockerfile, and then modify it in the running devcontainer to have the correct secret values.

Based on the above repro steps, it looks like something about the devcontainer build process is ignoring hidden files. I could just name the file without a starting period in the name and `COPY` _that_, but I feel like that shouldn't be necessary.  I **do not** have a `.dockerignore` file present in the `.devcontainer` folder. However, if I rebuild the devcontainer and click the "Starting Dev Container (show log)" notification in VS Code, I see the following log statements in a couple places:

```log
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
```

So I'm wondering if VS Code is adding some default `.dockerignore` file that ignores hidden files. I don't see anything in the [docker build](https://docs.docker.com/engine/reference/commandline/build/) or [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) docs to suggest that this caused by the Docker engine itself.

Now that this repo exists, I figured maybe VS Code is using this CLI under the hood, but let me know if there's a more appropriate repo at which to raise the Issue. Either way, if this issue _is_ caused by VS Code or the devcontainer CLI, then I request a way to override this in `devcontainer.json` so that we can include hidden files in our containers. 🙏

**EDIT**: Apparently the following Dockerfile command also works, so for some reason hidden files are only excluded when copying the _whole_ build context:

```Dockerfile
COPY .cdk.json /root/.cdk.json`
```

**Comment by chrmarti** [comment]
We use the `docker` CLI for building the image. It appears `.*` is excluded by default, see https://docs.docker.com/engine/reference/builder/#dockerignore-file. Maybe having a `.dockerignore` file with `!.*` would revert that default?

**Comment by Rabadash8820** [comment]
Hi @chrmarti, I don't see that rule mentioned in the docs. Are you talking about the warning at the end, where it says "For historical reasons, the pattern `.` is ignored."? I took that to mean that `.` is ignored, not `.*`. I suppose this could be easily tested by running `docker build` manually and seeing if it copies hidden files. I'll get to that if I have time today. If that _is_ the Docker default, I suppose there's no sense fighting it; might just worth a call out in the docs.

**Comment by Rabadash8820** [comment]
Hey @chrmarti, sorry for not getting back sooner. Turns out I just wasn't using `ls -a` when I listed files in my container. 🤦‍♂️ When building a devcontainer as described above or just building an image with `docker build`, I can confirm that hidden files _are_ being copied. I feel pretty sheepish. Gonna close this issue now and hope nobody ever googles it. 😅
