### ISSUE TITLE
Support specifying additional mounts in `up` command

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/cli#327]
In some contexts, it would be useful to be able to specify additional mounts that should be combined with those specified in the `devcontainer.json`.

An example is in `devcontainers/ci` to allow additional mounts to support GitHub actions behaviours such as the change to use `echo myOutput=123 >> $GITHUB_OUTPUT` instead of `echo "::set-output name=version::123" ([link](https://github.com/devcontainers/ci/issues/188))

**Comment by stephenandary** [comment]
I wouldn't mind giving this a go if that is okay

**Comment by stuartleeks** [comment]
Ignore me... it has been pointed out that this is [already suppported](https://github.com/devcontainers/cli/blob/main/src/spec-node/devContainersSpecCLI.ts#L112)!
