### ISSUE TITLE
`devcontainer` local features doesn't work on Windows

### ISSUE THREAD

**Issue by BusHero** [devcontainers/cli#350]
## Environment
1. Windows

## Steps to reproduce
1. Clone the [repo](https://github.com/BusHero/devcontainer-bug-localfeature-windows)
2. run `test.ps1`

### Expected result
Dev container is build

### Actual result
The following error gets generated
![image](https://user-images.githubusercontent.com/24370515/210285771-de619117-9539-4832-b1cf-07ea9438e614.png)

**Comment by joshspicer** [comment]
Thanks for the report @BusHero !  This should be resolved by https://github.com/devcontainers/cli/pull/333, which is merged into this repo but yet publish ed to NPM.

I've tested building your example dev container from `main` of this repository, and it succeeds 🚀 .  

We'll start up releases again this week and adopt these changes into Codespaces and the Dev Containers extensions after that.

**Comment by joshspicer** [comment]
`v0.27.0` should fix this. Please let me know if it doesn't :)
