### ISSUE TITLE
misspelled `platform` in `From` interface

### ISSUE THREAD

**Issue by ShauryaAg** [devcontainers/cli#357]
https://github.com/devcontainers/cli/blob/338857f87ffd00b0d5161ee6fbabf21eb8c3af05/src/spec-node/dockerfileUtils.ts#L38

`platform` is misspelled in `From` interface.

**Comment by joshspicer** [comment]
Thanks for highlighting!  I'll fix the typo as a commit on this somewhat-related PR: https://github.com/devcontainers/cli/pull/352/commits/1d15155e9d515c5a0eb38779ea9e4894a527e71c

**Comment by samruddhikhandale** [comment]
Closing as fixed with `v0.27.1` 🚀
