### ISSUE TITLE
Random "Is the docker daemon running?" with Docker-in-Docker Feature

### ISSUE THREAD

**Issue by metaskills** [devcontainers/cli#383]
I make heavy use of docker-in-docker and have noticed across a few projects that use (https://github.com/devcontainers/ci) randomly failing with the following message. NOTE: I never see this message in Codespaces, only when using the CLI via CI project.

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

At first I thought I needed to wait for docker to start up and I tried adding something like this to my `postCreateCommand` script:

```shell
timeout 60s bash -c 'until docker info; do sleep 5; done'
```

However it turns out that something lower level was going wrong. The logs always showed this error when the issue happened shortly after the devcontainer was created:

```
2023-01-22T19:03:04.2136493Z [2023-01-22T19:03:04.213Z] Container started
2023-01-22T19:03:04.5278182Z [2023-01-22T19:03:04.527Z] Running the postCreateCommand from devcontainer.json...
2023-01-22T19:03:04.5818191Z [2023-01-22T19:03:04.581Z] sed: couldn't flush stdout: Device or resource busy
```

This led me to investigate the following issues which may be related:

* https://github.com/devcontainers/cli/issues/70
* https://github.com/devcontainers/cli/issues/78

I tried adding `"privileged": true,` to my JSON in the hopes this would help and it did not. Random failures still occur. If it helps, here are some log outputs to compare.  These are pulled from 

* [GitHub Devcontainer w/Docker-in-Docker Action: Success](https://gist.github.com/metaskills/f6f7ddb777e0fc662e33278714f3fa6b)
* [GitHub Devcontainer w/Docker-in-Docker Action: Random Failure](https://gist.github.com/metaskills/4542aa54d779d1f265804eadd4b1fec7)

| Success | Failure |
| --- | --- |
| ![success](https://user-images.githubusercontent.com/2381/213936374-698aa9d5-639e-47e6-8cb1-b16eac09d71d.png) | ![failure](https://user-images.githubusercontent.com/2381/213936381-daf5e61f-7d42-46e8-8c23-f2a39752a636.png) |

In the work I am doing for this project (https://github.com/customink/crypteia/tree/MultiPlatform) I have set each job's test to do a simple `docker inspect` to fail fast and you can see where it fails further up in my postCreate script which is doing a docker run command. But make no mistake, even if that postCreate were removed the random failures would happen because the devcontainer somehow is not in a good state with docker-in-docker. Been seeing this on other project's CI as well.

**Comment by metaskills** [comment]
OK, this is straight up a bug with the Docker-in-Docker feature with its usage with the CI feature. It could be a CLI bug since I have not seen this issue with Codespaces. I made a very basic repo that demonstrates this happens ~20% (crude math) of the time. See here:

* https://github.com/customink/dnd-demo (repo)
* https://github.com/customink/dnd-demo/actions/runs/3981703221 (failure demo)

![failure](https://user-images.githubusercontent.com/2381/213942551-b1faa588-3522-43e6-9232-78a52cccd8c2.png)

**Comment by metaskills** [comment]
Sorry, not sure why this was closed, reopened it. Since I am un-sure if the issue should be in one of these places or not:

- https://github.com/devcontainers/ci/issues/192
- https://github.com/actions/runner-images/issues/6980

**Comment by chrmarti** [comment]
Continuing in https://github.com/devcontainers/ci/issues/192.
