### ISSUE TITLE
devcontainer should return non-zero exit code if it fails

### ISSUE THREAD

**Issue by akhildevelops** [devcontainers/cli#413]
Hi,

`devcontainer features test -f color; echo $?` returns `0` though `/workspaces/devcontainer-features/src/color` is not present. It displays the error but returns zero.

It's difficult to catch issues in [CI Pipeline](https://github.com/akhildevelops/devcontainer-features/actions/runs/4183819226/jobs/7248666682). Ran against https://github.com/akhildevelops/devcontainer-features/tree/28e76f09b7ca3e78e18a47dd82ffaa965f4c7f03

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting, that's definitely a bug. I'll look into fixing it.

**Comment by samruddhikhandale** [comment]
Closing as fix is merged https://github.com/devcontainers/cli/pull/418 and will be included in the next release!
