### ISSUE TITLE
How to override the docker-compose project name used by devcontainer?

### ISSUE THREAD

**Issue by hpe-ykoehler** [devcontainers/cli#415]
When integrating with Jenkins I hit an issue where Jenkins's workspace folder is being used for docker-compose project name.  The issue is that the way Jenkins truncate long workspace folder name can cause them to start with an underscore symbol.  And when that happens, devcontainer fails.

See the example here where my jenkins folder was truncated to "_ap-models_additional_adjustment".  Since I have no control over the jenkins workspace, and ideally, I would not like to create a folder for the purpose of solving this.

Is there a way for me to tell devcontainer to use something else for the docker-compose project name?  As clearly, not all linux filesystem name can be valid docker-compose project name...

```
+ devcontainer up --workspace-folder . --remove-existing-container

[2023-02-15T06:53:26.822Z] @devcontainers/cli 0.29.0. Node.js v19.4.0. linux 3.10.0-1160.49.1.el7.x86_64 x64.
[2023-02-15T06:53:30.596Z] Start: Run: docker compose -f /var/lib/jenkins/workspace/_ap-models_additional_adjustment/.devcontainer/docker-compose.yml --profile * config
...
#5 naming to docker.io/library/dev_container_feature_content_temp done
#5 DONE 0.0s

[2023-02-15T06:53:35.565Z] Start: Run: docker compose --project-name _ap-models_additional_adjustment_devcontainer -f /var/lib/jenkins/workspace/_ap-models_additional_adjustment/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-jenkins/docker-compose/docker-compose.devcontainer.build-1676444015563.yml build

[2023-02-15T06:53:35.869Z] "_ap-models_additional_adjustment_devcontainer" is not a valid project name
[2023-02-15T06:53:35.874Z] Exit code 1
Error: Command failed: docker compose --project-name _ap-models_additional_adjustment_devcontainer -f /var/lib/jenkins/workspace/_ap-models_additional_adjustment/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-jenkins/docker-compose/docker-compose.devcontainer.build-1676444015563.yml build
```

**Comment by hpe-ykoehler** [comment]
Actually, since I use the Organisation folder plugin which takes care of creating the workspace and doing the git clone, I do not see that I have control over the workspace folder itself.

It would require me to create a folder, then copy all the content of the current workspace into the new folder, which really seems like a big hack here, and may be complicated since there are hidden files as well.

**Comment by hpe-ykoehler** [comment]
Note that I found this page https://code.visualstudio.com/remote/advancedcontainers/set-docker-compose-project-name
but it seems that doing this may cause 2 builds of the same project on the same node for 2 different branches to end up using the same docker-compose project name, would not that cause a problem?  

Ideally, I would like to be able to pass a string to which something unique gets appended, like a timestamp for example.

**Comment by hpe-ykoehler** [comment]
The solution in the above URL of using a .env file also does not appear to be honored by devcontainer cli (likely just VSCode).

**Comment by hpe-ykoehler** [comment]
ha, figure that devcontainer needs its own environment modified... got it working using
```
    environment {
        def COMPOSE_PROJECT_NAME = "${BUILD_TAG}"
    }
```

**Comment by NerdToMars** [comment]
> ha, figure that devcontainer needs its own environment modified... got it working using
> 
> ```
>     environment {
>         def COMPOSE_PROJECT_NAME = "${BUILD_TAG}"
>     }
> ```

do you know where place I should place these code?
