### ISSUE TITLE
Syntax error - can't find = in "-a." with features enabled

### ISSUE THREAD

**Issue by xec-abailey** [devcontainers/cli#454]
Howdy!

This morning I logged in as usual and rebuilt my dev container but received the following error: 

```
ERROR: failed to solve: rpc error: code = Unknown desc = 
failed to solve with frontend dockerfile.v0: failed to solve with 
frontend gateway.v0: rpc error: code= Unknown desc = 
Syntax error - can't find = in "-a". Must be of the form: name=value
```

After a bit of messing around with it (trying again using a local dev container to make sure that it wasn't caused by codespaces for some reason) I removed "features" from my devcontainer and attempted to rebuild and it worked fine

See [this thread](https://github.com/orgs/community/discussions/50251) for others that are experiencing this issue

**Comment by joshspicer** [comment]
Given the report above, it seems to be a case of not escaping containerEnv properly.  It was likely introduced in https://github.com/devcontainers/cli/pull/392/files#diff-fe757ed747d00188273214482dfeb49fe54d578827ab64f39741e886564ad81bR453

**Comment by jkeech** [comment]
The change in #392 needs to be updated to properly quote and escape env var values as described at https://docs.docker.com/engine/reference/builder/#env. It looks like it's not quoting and escaping today, and spaces in the ENV values is now causing it to break.
