### ISSUE TITLE
fails to run up and build on WSL

### ISSUE THREAD

**Issue by aaronenberg** [devcontainers/cli#471]
`devcontainer@0.31.0 ${HOME}/.vscode-remote-containers/dist/dev-containers-cli-0.282.0`
I installed through VSCode and am using WSL version 1.1.6.0 with Debian 10

I have the path to the installation on Windows host set in my Linux PATH.

Running `up` or `build` results in this error:
```
(node:28717) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: j7.randomUUID is not a function
    at Ks (/home/foo/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:4558)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async foe (/home/foo/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:25627)
    at async loe (/home/foo/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:25018)
{"outcome":"error","message":"j7.randomUUID is not a function","description":"An error occurred building the container."}
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

@aaronenberg are you still facing the issue here? If so, @alexander-smolyakov can you help investigate this? Thanks!

**Comment by alexander-smolyakov** [comment]
Hey @aaronenberg, the `TypeError: j7.randomUUID is not a function` error is related to the `crypto.randomUUID` function. This function was introduced in Node versions `>= v14.17.0`. Could you please check the Node version used in your environment and update it to the required or recent version?

https://github.com/devcontainers/cli/blob/86604a8e5a04d43e7ed73a615d0b2301ccb403b5/package.json#L17-L19

**Comment by alexander-smolyakov** [comment]
@aaronenberg, could you please provide an update? Is this issue still actual to you?

**Comment by alexander-smolyakov** [comment]
@aaronenberg, I'm closing this issue due to a lack of response. Feel free to request the reopening if the issue is still actual to you.
