### ISSUE TITLE
Support fetching Features|Templates by SHA digest

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/cli#479]
Just as docker image can be pulled [by digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier) instead of tags, Features and Templates should be able to be pinned to a SHA256 digest in the user `devcontainer.json`.  

This change requires no changes to published Features|Templates, only a change to the CLI to respect a provided SHA.

-----

Digests can be found on the GHCR package page for a published Feature: https://github.com/devcontainers/features/pkgs/container/features%2Fgit-lfs/82847789?tag=1

<img width="777" alt="image" src="https://user-images.githubusercontent.com/23246594/229860375-07ded780-7710-42a1-8c0c-f3312b4ae6ac.png">

It's also available as the [JSON response to the `devcontainer feature publish` command](https://github.com/devcontainers/features/actions/runs/4608512953/jobs/8144373610#step:3:412)
```jsonc
{
   // ...
   "git-lfs": {
      "publishedVersions" :["1","1.1","1.1.0","latest"],
      "digest":"9e0b6df853ec932203945b76b9cfa7470ebd1f8bd765484027608581f9cf8a77",
      "version":"1.1.0"
    }
}
```

**Comment by jkeech** [comment]
@joshspicer with this change, what would be the syntax in devcontainer.json? Would it be the following?

```
{
  "features": {
    "ghcr.io/devcontainers/features/git-lfs@sha256:9e0b6df853ec932203945b76b9cfa7470ebd1f8bd765484027608581f9cf8a77": {}
  }
}
```

**Comment by joshspicer** [comment]
Yes, I don't see any reason to not align with the pattern used elsewhere in the OCI/docker specs for container images.

The one caveat is that we currently detect the "v1" Features (that we hosted via GitHub Release) with the `@` symbol, but I believe we can get around that while also maintaining the back compat.

**Comment by joshspicer** [comment]
Version [0.39.0](https://github.com/devcontainers/cli/blob/main/CHANGELOG.md#0390) of the dev container CLI now supports pinning Features by digest.
