### ISSUE TITLE
adding `runArgs` not working as expected

### ISSUE THREAD

**Issue by behrica** [devcontainers/cli#492]
I had (repeatedly)  a hard time to get it work to add `"runArgs": ["--publish","12345:12345"],` to an existing `devcontainer.json`.

Changing the config files did not give any result (looking at `docker ps`)

Repeated `dev container build / up` including `no-cache` option did not have any effect.
Even apparent syntax errors in the devcontainer.json file did not result in "error messages"

It finally worked by running `docker container prune`  once, which I had never used before.

Is there maybe some "caching" somewhere, which ignores when `run-args` get added into `devcontainer.json` ?

**Comment by behrica** [comment]
I get the behaviour which I expect into 'devcontainer up' , when I add "--remove-existing-container".
So I would say, that it is "unclear", which changes into a `devcontainer.json` file require which "cleaning command" to become effective.
There are quite some possibilities :

* devcontainer build
* devcontainer up

each having options of "no cache" in some form.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Wondering, would improving documentation for `devcontainer up --help` and `devcontainer build --help` command help avoid the confusion? Let us know if you have other thoughts/ideas.

**Comment by samruddhikhandale** [comment]
Closing as stale. Feel free to reopen with details.
