### ISSUE TITLE
How can I use this cli in my extension?

### ISSUE THREAD

**Issue by taoqf** [devcontainers/cli#498]
Hello, I would like to know if I can use this in my extension? I don't want my extension users install nodejs in there computer, so they could not install this cli in there computer, so I wish to bundle the cli in my extension.

**Comment by samruddhikhandale** [comment]
Hi 👋 

I am positive that the CLI can be used within an extension, it is currently used by Dev Containers VS Code extension.

**Comment by taoqf** [comment]
thank you, but I cannot find source code of extension dev container.

**Comment by samruddhikhandale** [comment]
Unfortunately, that's not public. @chrmarti  / @bamurtaugh do we have any public examples of the cli usage in an extension?

**Comment by bamurtaugh** [comment]
We have a variety of CLI examples usages here: https://github.com/devcontainers/cli/tree/main/example-usage. While not directly in an extension, I think they'd be great reference points as you look to integrate it into your workflows!

**Comment by taoqf** [comment]
Thank you all, I will look into it.

**Comment by chrmarti** [comment]
The Dev Containers extension uses the CLI with the following difficulties:

The CLI requires the native module `node_pty` which needs to be compiled for the machine's architecture. The Dev Containers extension uses the `NODE_PATH` environment variable to get VS Code's version of that module loaded:
```ts
NODE_PATH=`${path.join(vscode.env.appRoot, 'node_modules.asar')}${path.delimiter}${path.join(vscode.env.appRoot, 'node_modules')}`
```

The Dev Containers extension uses VS Code's Electron binary to spawn (`child_process.spawn`) the CLI, maybe `child_process.fork` would work too. The binary's path is in `process.argv[0]` in the extension and if `process.versions.electron && process.versions['microsoft-build']` is truthy (which is the case with recent VS Code builds) `--ms-enable-electron-run-as-node` needs to be added as a CLI argument.

@taoqf Out of curiosity, can you share what you are working on?

**Comment by taoqf** [comment]
Same as https://github.com/microsoft/vscode-remote-release/issues/8422
