### ISSUE TITLE
simplest setup, but cannot write files (permisson error)

### ISSUE THREAD

**Issue by craigphicks** [devcontainers/cli#504]
`devcontainer@0.35.0`
`Docker version 23.0.4, build f480fb1`
`Docker Compose version v2.17.2`

```
.devcontainer
  |-  .devcontainer.json
  |-  Dockerfile
```

.devcontainer.json:
```
{
    "name": "Node.js",
    "build": {
        "dockerfile": "Dockerfile",
    },
    "settings": {
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.profiles.linux": {
            "bash": {
                "path": "/bin/bash",
                "icon": "terminal-bash",
            },
        },
    },
    "extensions": [
        "dbaeumer.vscode-eslint"
    ],
}
```

Dockerfile:
```
FROM mcr.microsoft.com/devcontainers/typescript-node:20
```

```
$ devcontainer build .
[12 ms] @devcontainers/cli 0.35.0. Node.js v16.14.2. linux 5.15.0-41-generic x64.
[519 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-craig/container-features/0.35.0-1682146167065/Dockerfile-with-features -t vsc-testdevc-badaeb5eab5ce3c45f2eb0d49d69644c94fb162ab4a701e8569eeb7219cdbf07 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/craig/testDevc/.devcontainer
[+] Building 0.1s (6/6) FINISHED                                                
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 1.38kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/typescri  0.1s
 => CACHED [dev_container_auto_added_stage_label 1/1] FROM mcr.microsoft.  0.0s
 => preparing layers for inline cache                                      0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:0fa55cc0ebea427319bfb7cb68823433bc84e04ebb016  0.0s
 => => naming to docker.io/library/vsc-testdevc-badaeb5eab5ce3c45f2eb0d49  0.0s
{"outcome":"success","imageName":["vsc-testdevc-badaeb5eab5ce3c45f2eb0d49d69644c94fb162ab4a701e8569eeb7219cdbf07"]}
```

```
$ devcontainer open
[229 ms] @devcontainers/cli 0.35.0. Node.js v16.14.2. linux 5.15.0-41-generic x64.
```

From the vscode terminal inside the container
```
node ➜ /workspaces/testDevc $ ls -al
total 12
drwxrwxr-x 3 root root 4096 Apr 22 06:49 .
drwxr-xr-x 3 root root 4096 Apr 22 06:49 ..
drwxrwxr-x 2 root root 4096 Apr 22 06:49 .devcontainer
node ➜ /workspaces/testDevc $ ls -an
total 16
drwxrwxr-x 3 0 0 4096 Apr 22 07:11 .
drwxr-xr-x 3 0 0 4096 Apr 22 06:49 ..
drwxrwxr-x 2 0 0 4096 Apr 22 06:49 .devcontainer
node ➜ /workspaces/testDevc $ whoami
node
node ➜ /workspaces/testDevc $ id
uid=1000(node) gid=1000(node) groups=1000(node),998(nvm),999(npm)
node ➜ /workspaces/testDevc $ groups
node nvm npm
node ➜ /workspaces/testDevc $ cat > test.txt
bash: test.txt: Permission denied
node ➜ /workspaces/testDevc $ 
```

From a terminal outside the container:
```
craig@desk:0:~/testDevc$ ls -al
total 16
drwxrwxr-x  3 craig craig 4096 Apr 22 00:11 .
drwxr-xr-x 55 craig craig 4096 Apr 21 23:48 ..
drwxrwxr-x  2 craig craig 4096 Apr 21 23:49 .devcontainer
craig@desk:0:~/testDevc$ whoami
craig
craig@desk:0:~/testDevc$ id
uid=1000(craig) gid=1000(craig) groups=1000(craig),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare),255(common),998(docker),1001(craig1001)
craig@desk:0:~/testDevc$ cat > test2.txt
hello
craig@desk:0:~/testDevc$ cat test2.txt
hello
```

As you can see, user `craig` on the host and user `node` on the container share the same uid.  I though that was enough to ensure that `node` would be able to write files.

What am I missing?  Could it be because the host is ubuntu linux and not a WSL?

**Comment by craigphicks** [comment]
To make analysis and solution more simple I simplified to using `docker` alone (without `devcontainer`) and confirmed the same phenomena with a simple Docker container.  I also found a workaround so that host and container can share reading and writing of files.  I post it below.  I think it can probably be applied without interfering with `devcontainer`.  But I would still like to know if `devcontainer` offer a more simple solution.

------------------------------------------

### Create a docker container where the container and host can share read and write access to a mounted home directory.

### 1. Set up the container 

#### 1.1. Prepare the Dockerfile

Change to the directory that will be used for testing (here is it `~/github/dsd`).

```
FROM ubuntu
ARG USERNAME=duser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN apt-get update 
RUN groupadd --gid $USER_GID $USERNAME \
   && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
   && apt-get update \
   && apt-get install -y sudo \
   && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
   && chmod 0440 /etc/sudoers.d/$USERNAME 
```


#### 1.2 Build the image from the Dockerfile file.
```
docker build -t testi . 
``` 

#### 1.3 Create a container from the image.
```
docker run --rm -u 1000:1000 -d -it --name testc --mount type=bind,source="$(pwd)",target=/devdir testi
```

#### 1.4 Attach the container 
```
docker attach testc
```

#### 1.5 From inside the container .... 

```
duser@71a653791192:/$ ls     
bin   dev     etc   lib    lib64   media  opt   root  sbin  sys  usr
boot  devdir  home  lib32  libx32  mnt    proc  run   srv   tmp  var
duser@71a653791192:/$ cd devdir
duser@71a653791192:/devdir$ ls -alt
total 16
drwxr-xr-x 1 root root 4096 Apr 22 18:01 ..
-rw-rw-r-- 1 root root 1530 Apr 22 18:01 README.md
-rw-rw-r-- 1 root root  507 Apr 22 17:37 Dockerfile
drwxrwxr-x 2 root root 4096 Apr 22 17:30 .
duser@71a653791192:/devdir$ ls -n
total 8
-rw-rw-r-- 1 0 0  507 Apr 22 17:37 Dockerfile
-rw-rw-r-- 1 0 0 1530 Apr 22 18:01 README.md
```
From inside the container `devdir` and its contents appears to be owned by root.
Change `devdir` and its contents to be owned by duser:duser instead.

```
duser@71a653791192:/devdir$ sudo chown -R duser:duser ../devdir
```
Check the files have changed
```
duser@71a653791192:/devdir$ ls -alt
total 16
drwxr-xr-x 1 root  root  4096 Apr 22 20:25 ..
-rw-rw-r-- 1 duser duser 2334 Apr 22 20:24 README.md
-rw-rw-r-- 1 duser duser  507 Apr 22 17:37 Dockerfile
drwxrwsr-x 2 duser duser 4096 Apr 22 17:30 .
duser@71a653791192:/devdir$ ls -n
total 8
-rw-rw-r-- 1 1000 1000  507 Apr 22 17:37 Dockerfile
-rw-rw-r-- 1 1000 1000 2334 Apr 22 20:24 README.md
duser@71a653791192:/devdir$ touch touched1.txt
duser@71a653791192:/devdir$ ls -l touched1.txt
-rw-r--r-- 1 duser duser 0 Apr 22 20:30 touched1.txt
```

### 2. Enable host read and write 

#### 2.1 From outside the container .... 

From the test directory `~/github/dsd`
```
craig@desk:0:~/github/dsd$ ls -alt
total 20
-rw-rw-r--  1 100999 g100999 4151 Apr 22 13:51 README.md
-rw-rw-r--  1 100999 g100999  482 Apr 22 13:46 Dockerfile
drwxrwsr-x  2 100999 g100999 4096 Apr 22 13:30 .
-rw-r--r--  1 100999 g100999    0 Apr 22 13:30 touched1.txt
drwxrwxr-x 90 craig  craig   4096 Apr 22 10:28 ..
```

It turns out, in this case, that container user uid and gid of 1000 on the container get mapped to uid and gid of 100999 on the host.  This is probably highly dependent on the system and environment, etc.  

#### 2.2 Add group on host 

On the host create a group with gid 100999, and add the host user to that group.  It is necessary to log out and log back in again for it to take effect. (*)

```
sudo addgroup --gid 100999 g100999
sudo usermod -a -G g100999 craig
```
(*Note, when deleting a group with `passwd -d ...`, logging out and in again may be insufficient, it may require a reboot - as it for me.)

#### 2.3 Change group permissions for dirs and files

Ensure the whole directory and all its subdirectories have group read, write, executable, and setuid permissions.  (They probably already do for rwe, but maybe not s).
```
sudo find . -type d -exec chmod g+rwxs {} +
```

Ensure the all files in all subdirectories have group read and write permissions:
```
sudo find . -type f -exec chmod g+rw {} +
```

Test that files can be modifed:
```
craig@desk:0:~/github/dsd$ touch touched1.txt
```
If there no error, success has been achieved.

### 2.4 Considerations

It would be better to manipulate the permissions before building the container, if the user container id mapping to host is known in advance.

There maybe a much cleaner way to do this - I originally thought it would happen transparently by giving the container user the same id as the host user outside the container.  On the other, it may offer more security to have it map a different uid/gid outside the container.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for opening this issue and providing a summary of your investigation.

> (I don't understand why the container user id of 1000 appears as 100999 on the host, but as long as it is constant, it doesn't matter).

@alexander-smolyakov Could you investigate and see if it's a bug or its expected per design? Thanks!

**Comment by craigphicks** [comment]
@samruddhikhandale  - Hello and thank you for your reply.  Accord to the man page for "subuid" on my host system (ubuntu 20)

> Each line in `/etc/subuid` contains a user name and a range of subordinate user ids that
       user is allowed to use. This is specified with three fields delimited by colons (“:”).
       These fields are:
       •   login name or UID
       •   numerical subordinate user ID
       •   numerical subordinate user ID count
       This file specifies the user IDs that ordinary users can use, with the newuidmap command,
       to configure uid mapping in a user namespace.

There is an almost identical page for "subgid", about group ids.

Both my subuid and subgid files contain:
```
craig:100000:65536
```

From the description and because I think user ids begin at 1000, my first guess would be that user 1000 on the docker container would map to 100000 on the host, because it the first possible user id.  Failing that my second guess would be 101000.  Not sure where 100999 came from.

**Comment by alexander-smolyakov** [comment]
> (I don't understand why the container user id of 1000 appears as 100999 on the host, but as long as it is constant, it doesn't matter).

Hey @craigphicks, it seems to be related to Docker Desktop. The Docker mounts root to the current user, and other users inside the container get a user and group id based on some range. 

Here is a related issue that could provide more context regarding weird uid/gids on host machine:
- https://github.com/docker/desktop-linux/issues/31

**Comment by alexander-smolyakov** [comment]
@craigphicks, could you please let us know if you have other questions regarding this issue?

**Comment by craigphicks** [comment]
> @craigphicks, could you please let us know if you have other questions regarding this issue?

@alexander-smolyakov - It seems [this MS answer](https://github.com/docker/desktop-linux/issues/31#issuecomment-1161606016) is an "idea" level answer, and the recipe I gave here is that answer with the details filled in - especially the need for `umask 0002` which wasn't mentioned in your link.

I'm surprised there isn't enough demand for container-host RW file sharing that this how-to information was already in the vscodes `devcontainer` documentation.
