### ISSUE TITLE
computeInstallationOrder does not work when specifying features via repository url

### ISSUE THREAD

**Issue by brian-mcnamara** [devcontainers/cli#506]
When using absolute URLs for features, computeInstallationOrder reduces the feature set to the last entry. This is caused due to https://github.com/devcontainers/cli/commit/dc23b12bafc8fa0eac43fb1b1daccef8ba17ce82 which is now mapping the features to be a key by `feature.feature.sourceInformation.userFeatureId.split(':')[0]` which for the case where you specify a URL would be `https` for example. 

What results is the calculated install order will only contain a single entry if multiple features are using a url link to the tarball

**Comment by samruddhikhandale** [comment]
Thanks for reporting the bug, appreciate it!

**Comment by brian-mcnamara** [comment]
#530 fixes this
