### ISSUE TITLE
Unable to write file due to `EACCES: permission denied`

### ISSUE THREAD

**Issue by piquark6046** [devcontainers/cli#513]
I cannot write a file in subdirectory of a repository, but writing files under the repository is OK.
I enabled docker rootless.

### Behavior of the bug

[Screencast from 2023-05-04 01-10-34.webm](https://user-images.githubusercontent.com/98787049/235975652-8783316a-3bbf-4c72-92ae-4e5c6aef32cb.webm)

### Environment
No changes in `/etc/docker/daemon.json` or `~/.config/docker/daemon.json`.
Operating System: Ubuntu 23.04
<details><summary>Docker info</summary>

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.2.0-20-generic
 Operating System: Ubuntu 23.04
 OSType: linux
 Architecture: x86_64
 CPUs: [Hidden]
 Total Memory: [Hidden]
 Name: piqua-Desktop
 ID: [Hidden]
 Docker Root Dir: /home/piqua/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

</details> 

### Context of the `devcontainer.json`:
<details><summary>Click to view</summary>

```json
{
  "name": "Node.js & TypeScript",
  "image": "mcr.microsoft.com/devcontainers/typescript-node:0-20",
  "features": {
  "ghcr.io/supermatt/devcontainer-features/uid-gid-fixer:latest": {},
  "ghcr.io/devcontainers/features/node:1": {
    "nodeGypDependencies": true,
    "version": "lts"
  },
  "ghcr.io/devcontainers/features/rust:1": {
    "version": "latest",
    "profile": "default"
  },
  "ghcr.io/devcontainers-contrib/features/bash-command:1": {
    "command": "echo hi!"
  },
  "ghcr.io/devcontainers-contrib/features/npm-package:1": {
    "package": "typescript",
    "version": "latest"
  }
  }
}
```

</details>

### Permission of each directory

<details><summary>Host</summary>

![Screenshot_from_2023-05-04_01-06-18 cleaned](https://user-images.githubusercontent.com/98787049/235980185-bc24630b-353b-4425-824d-64b89577f1be.png)
![Screenshot_from_2023-05-04_01-06-09 cleaned](https://user-images.githubusercontent.com/98787049/235980197-0e83cc37-efb1-4baf-9d51-f7510a7cf47f.png)

</details> 

<details><summary>Container</summary>

![Screenshot from 2023-05-04 01-34-59](https://user-images.githubusercontent.com/98787049/235981504-8487244d-03cb-4c14-a2a8-32666d7ebbd2.png)

</details>

**Comment by chrmarti** [comment]
Please use `ls -la` to check the permissions. (`id` shows the id and groups of the current user)

The folder might me owned by root in the container and your user on the local machine (rootless does the mapping).

**Comment by piquark6046** [comment]
Here you are:

<details><summary>Host</summary>

![Screenshot_from_2023-05-04_17-27-02 cleaned](https://user-images.githubusercontent.com/98787049/236152794-153208ef-7d1d-4fbe-a32b-7066bc8cbfd4.png)
![Screenshot_from_2023-05-04_17-27-13 cleaned](https://user-images.githubusercontent.com/98787049/236152804-a96584b3-1d1e-4486-9bb6-38d187d38a42.png)

</details> 

<details><summary>Container</summary>

![Screenshot_from_2023-05-04_17-33-15 cleaned](https://user-images.githubusercontent.com/98787049/236152903-ae8e0f23-e570-4bed-aa4a-48305ebba5b7.png)
![Screenshot_from_2023-05-04_17-33-04 cleaned](https://user-images.githubusercontent.com/98787049/236152912-4c0f48e0-ecc9-464c-a8b0-f95ac7b109c3.png)


</details>

**Comment by piquark6046** [comment]
Thanks you. Your suggestion works.

**Comment by R0Wi** [comment]
@chrmarti is there also a solution when running with a non-root container user like `"remoteUser": "vscode"` (where `vscode` has UID 1000 for example)?
