### ISSUE TITLE
[Feature request] pass --dockerfile to devcontainer build command

### ISSUE THREAD

**Issue by sliekens** [devcontainers/cli#529]
Hi,

I'm struggling to understand the correct way to pre-build dev container images and I'm starting to think it's just not possible to do what I want.

I followed the steps from https://code.visualstudio.com/docs/devcontainers/devcontainer-cli#_prebuilding

My devcontainer.json

``` json
{
  "name": "my-project",
  "dockerFile": "Dockerfile"
}
```

My command to build and push it:

``` sh
devcontainer build --image-name ghcr.io/sliekens/my-project/devcontainer --push
```

This is where the documentation ends, but we're not done, are we? Because nothing actually references the pre-built image.

I think the best way to proceed is to update the devcontainer.json. This way, users will (only) use the pre-built image. 

``` diff
{
  "name": "my-project",
-  "dockerFile": "Dockerfile"
+  "image": "ghcr.io/sliekens/my-project/devcontainer"
}
```

However, now my build command stops working because I removed the path to the Dockerfile.

```
[23 ms] remote-containers 0.251.0.
Error: --platform or --push require dockerfilePath.
    at _k (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:12390)
    at async kk (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:9731)
{"outcome":"error","message":"--platform or --push require dockerfilePath.","description":"--platform or --push require dockerfilePath."}
```

So I checked `devcontainer build --help` to see how I can pass the `dockerfilePath`, only to find it's actually not implemented.

What I'd like to do is reference the image in my devcontainer.json:

``` json
{
  "name": "my-project",
  "dockerFile": "ghcr.io/sliekens/my-project/devcontainer"
}
```

Then, I would like to build the image from a Dockerfile, without altering the configuration:

``` sh
devcontainer build --dockerfile .devcontainer/Dockerfile --image-name ghcr.io/sliekens/my-project/devcontainer --push
```

**Update**

I think I did find a good way to do what I want using `cacheFrom`. I believe this is currently the best way to do pre-built images but I'm not 100% sure. Information is a bit scarce.

``` json
{
  "name": "my-project",
  "dockerFile": "Dockerfile",
  "build": {
    "cacheFrom": "ghcr.io/sliekens/my-project/devcontainer"
  },
}
```

``` sh
devcontainer build --no-cache --image-name ghcr.io/sliekens/my-project/devcontainer --push --workspace-folder .
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

Let me see if I've understood your use case, you are looking to prebuild an image (which is built from a dockerfile) and then use that prebuilt image. Is my understanding correct? 

If so, then you would need two dev containers. Have you looked at https://github.com/devcontainers/ci ? It will help to build &  publish the image from your dev config 1. Then, you can create a second dev config which references the pushed image - which you can use to build the dev container for your repo/project.

**Comment by sliekens** [comment]
Thanks, @samruddhikhandale 

Your understanding is correct.

> If so, then you would need two dev containers.

I feared this was the case but I really don't want to maintain 2 dev container configs. What do you think of my approach of using a single dev container config with Dockerfile and `cacheFrom` the prebuilt image? I've only been using it for a day but it seems good.

**Comment by sliekens** [comment]
Ahaaaaa, I think my feature request no longer makes sense given this information.
