### ISSUE TITLE
Export buildx remote cache when using devcontainer build command

### ISSUE THREAD

**Issue by yokonao** [devcontainers/cli#563]
## Problem
Currently, we are using the `--cache-to` option of the docker buildx build command to export the build cache to a registry or local file system. However, the devcontainer build command only has the --cache-from option and not the --cache-to option, which makes exporting the build cache impossible.

## Proposal
We would like to request the addition of the `--cache-to` option to the devcontainer build command, which would allow us to export the build cache. This would enable developers to export and reuse the build cache.

**Comment by bamurtaugh** [comment]
Thank you for opening this!

I think we'd welcome a PR if you're interested in taking a pass at implementing this. cc @chrmarti for other thoughts.
