### ISSUE TITLE
Commands Specified in devcontainer.json Fail in GitHub Actions

### ISSUE THREAD

**Issue by Olgethorpe** [devcontainers/cli#606]
I have a CI/CD pipeline that utilizes devcontainers/ci to run relevant test/build commands using GitHub Actions. Prior to the release of [devcontainers/cli 0.50.1](https://www.npmjs.com/package/@devcontainers/cli?activeTab=readme). All of the devcontainers were able to execute their commands without any issues. Now executing any of the commands after the `initializeCommand` fail inside of the GitHub Actions runner where they were not before. If I do not specify a `runCmd` in the devcontainers/ci action's arguments the devcontainer is still able to be built. The devcontainers are able to be built and ran locally when using VSCode and everything works as expected. 

What I do know when this executes is as follows:

1. The devcontainer is able to be built
2. Upon attempting any command past the `initializeCommand` it fails with the following error: `the input device is not a TTY` without any additional explanation

At first I thought some combination of `runArgs` I could supply to make the devcontainer work again but that does not seem to be the case. Would a feature to use a specific version of the devcontainers CLI be worth implementing?

**Comment by chrmarti** [comment]
Fixed in 0.50.2. Let me know if you still see any issues with that. Thanks!

**Comment by Olgethorpe** [comment]
> Fixed in 0.50.2. Let me know if you still see any issues with that. Thanks!

I can confirm, that CI/CD jobs in GitHub actions are no longer reporting the `the input device is not a TTY` error. Thank you for getting the fix out quickly!
