### ISSUE TITLE
cliHost.ts: connectLocal function and cygwin/mingw unix socket files

### ISSUE THREAD

**Issue by amurzeau** [devcontainers/cli#62]
Hi,

I'm wondering what this code is supposed to to, is it supposed to be able to connect to cygwin unix-domain sockets files ?
https://github.com/devcontainers/cli/blob/839ef66ae95820b41b3faec09764e6d30fc8abb4/src/spec-common/cliHost.ts#L93-L107

In https://github.com/microsoft/vscode-remote-release/issues/6719 , I've found that a modification to this function can allow VSCode to forward Git Bash's ssh-agent socket file (which use the cygwin unix domain sockets format).

Would a PR be welcome to change this function to handle cygwin unix-domain sockets files ?

**Comment by chrmarti** [comment]
The current code handles socket paths on Windows (parsing port and GUID from the file at the path, https://github.com/microsoft/vscode-remote-release/issues/72). What did you have to change to make it work with Cygwin socket paths? (PR welcome.)
