### ISSUE TITLE
Does the CLI support Windows Based Images

### ISSUE THREAD

**Issue by RollsChris** [devcontainers/cli#633]
Hi I'm having trouble running dev containers when docker is set to windows containers?

Is this a known thing? thanks

**Comment by samruddhikhandale** [comment]
Hi 👋 

Looks like you are expecting a Windows dev container to work with your setup? We have https://github.com/microsoft/vscode-remote-release/issues/445 open for adding support for Windows Containers.

**Comment by RollsChris** [comment]
That's abit disappointing, so to use Dev containers as a .net developer means I have to use bash or the Linux version of power shell?
