### ISSUE TITLE
dev container 'features' vscode-specific properties should be nested under `customizations.vscode`

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/cli#65]
Per the ["supporting tools" spec](https://github.com/devcontainers/spec/blob/main/docs/specs/supporting-tools.md), and to reduce confusion, we should migrate the three vscode-specific properties to be nested under `customizations`

The features proposal spec should also be updated to include these properties at the same time as the reference implementation: https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md

**Comment by chrmarti** [comment]
The CLI has code updating existing features to use "customizations" (https://github.com/devcontainers/cli/blob/b7dc6fe5a406fda55e694ec126634c91d4a96198/src/spec-configuration/containerFeaturesConfiguration.ts#L609) for compatibility. The schema needs to be updated.

**Comment by jkeech** [comment]
The schema was updated in https://github.com/devcontainers/spec/pull/65. Closing as completed, but please re-open if there's more to do here.
