### ISSUE TITLE
A command to rebuild the environment

### ISSUE THREAD

**Issue by s1n7ax** [devcontainers/cli#651]
I could not find a way to rebuild the environment after making some changes to `devcontainer.json`. I can manually delete the container using docker cli and re run `devcontainer up --workspace-folder .` but I think it would be convenient command to have within devcontainer.

**Comment by hpe-ykoehler** [comment]
I normally use --remove-existing-container when I make a change to .devcontainer.   I wish that like VSCode the devcontainer CLI tools was able to detect a change in those files and re-built itself as needed.

**Comment by s1n7ax** [comment]
That's good to know. I've been removing containers using docker cli.
