### ISSUE TITLE
Confused, @vscode/dev-container-cli or @devcontainers/cli

### ISSUE THREAD

**Issue by fvelcker** [devcontainers/cli#66]
Hello,

I am confused, the more I try to fix my access denied (https://github.com/devcontainers/cli/issues/60#issuecomment-1166283548), the more confuse I am. Should we @vscode/dev-container-cli or @devcontainers/cli ?
It seems to have mixed messages accross documentation and different issue board.

Can anyone make it clear for me please?

**Comment by bamurtaugh** [comment]
Thanks for opening @fvelcker!

You should use `@devcontainers/cli`, which is the CLI from this repo. It serves as the reference implementation for the dev container specification. `@vscode/dev-container-cli` is an older "Remote-Containers CLI" that could be installed within the Remote-Containers extension or through the command line.

We're currently tracking renaming the older Remote-Containers CLI ([issue](https://github.com/microsoft/vscode-remote-release/issues/6424)), and replacing the Remote-Containers CLI with the newer one in current tooling ([issue](https://github.com/microsoft/vscode-remote-release/issues/6859)).

Please let me know if you have any other questions!

**Comment by fvelcker** [comment]
@bamurtaugh thanks for the clarification
