### ISSUE TITLE
 How to customize the name of the container?

### ISSUE THREAD

**Issue by Brantfang** [devcontainers/cli#668]
How to customize the name of the container?（devcontainer up --workspace-folder）
What does the name field in the configuration file represent? for UI what is mean?

**Comment by bamurtaugh** [comment]
A command like this should work:

`devcontainer build --workspace-folder <location_of_folder> --push true --image-name <image name I want to use, like docker_publisher/image_name:latest>`

Please let me know if you were looking for something else!

**Comment by Brantfang** [comment]
@bamurtaugh Thanks.
