### ISSUE TITLE
Add a `devcontainer open` flag to open up a repo in VS Code in the dev container

### ISSUE THREAD

**Issue by craigloewen-msft** [devcontainers/cli#695]
In the command line I want to open VS Code and have it open directly into my dev container. 

Right now I do this by running `code .` and then clicking the "Reopen in container" button but I'd love to just open straight to the project.

Something like: `devcontainer open .` would address my feedback and help me out a lot.

Thanks!

**Comment by eljog** [comment]
Hi @craigloewen-msft thank you for submitting this issue.
The devcontainers CLI is agnostic of the editor tools, so it may not fit well to add an `open .` command to launch vscode.
While understand this is not exactly what you are looking for, have you considered using the `Open Recent` (Ctrl+R) option inside vscode?

If you think it can be beneficial if the vscode extension can detect the container and automatically re-open the workspace folder in container, please consider filing an issue at https://github.com/microsoft/vscode-remote-release/issues
