### ISSUE TITLE
Request: subcommand to download and unpack feature

### ISSUE THREAD

**Issue by jeffb4** [devcontainers/cli#697]
Problem: There is currently no purpose-built tool to download and unpack `application/vnd.devcontainers` .

What I'm trying to do: I am trying to create a build for something-like a devcontainer without requiring a `@devcontainers/cli` npm installation on the building host. So, within a build context I would like a utility to download and unpack features.

Example: `devconatiner features fetch ghcr.io/devcontainers/features/docker-in-docker:2 /tmp/dind` would download the tarball for `ghcr.io/devcontainers/features/docker-in-docker:2` and unpack to `/tmp/dind`. Optionally dependencies could be downloaded as well.

**Comment by joshspicer** [comment]
There's been some discussion on a similar `vendor` command for a different purpose https://github.com/devcontainers/cli/issues/399

**Comment by joshspicer** [comment]
Note that you may be able to leverage the [`oras` CLI](https://oras.land/) (similar to how it's spelled out in the spec [here](https://containers.dev/implementors/features-distribution/#oci-registry)) to achieve your goal

**Comment by jeffb4** [comment]
@joshspicer `oras` works perfectly (I tried `skopeo` and `umoci` without much success), thanks a ton.

Closing, since it works so well.
