### ISSUE TITLE
Incorrect text for CLI help output for terminal rows and columns

### ISSUE THREAD

**Issue by GaTechThomas** [devcontainers/cli#733]
When using `--help` for several devcontainer commands, the description for rows and columns seems to be mixed up:

```
  --terminal-columns              Number of rows to render the output for. This is required for some of the subprocesses to correctly render their output.  [number]
  --terminal-rows                 Number of columns to render the output for. This is required for some of the subprocesses to correctly render their output.  [number]
``` 

It would seem that `--terminal-columns` should reference `columns` instead of `rows` as shows above. ...and vice versa.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for catching this error, it looks like a mixup to me as well.
