### ISSUE TITLE
Correct USER after features stage: Investigate other cases

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/cli#78]
#70 follow-up

https://github.com/devcontainers/cli/blob/c67f5c8873dbd75864a098301c9a8db35383082c/src/spec-node/utils.ts#L344

Multi-stage builds could result in the current approach returning the wrong user.

Also: Variables are not supported.

Considering the possible cases an alternative approach might work better (if one exists).

**Comment by Chuxel** [comment]
One thought here - why don't we simply chain this into the actual ENTRYPOINT for the container image as a pre processing step?  We can get the existing entrypoint and invoke it afterwards as an arg set.  (Using `exec "$@"`).  That also removes the need to reference the feature to get the entrypoint to apply... and it would automatically use whatever the container user was.

**Comment by chrmarti** [comment]
The difficulty is with us temporarily setting `USER root` for the feature install scripts and then having to go back to `USER <previous>`. When features were built in a separate image (`FROM <user image>`), we did inspect the user image and pass its user as a build argument. Now that we build the user image and add the features in a single `Dockerfile` (for caching checksums and multi-arch builds), I haven't yet found a way to determine the user before we change it to root and then go back to it with `USER`.

E.g., if `ENV` would support command substitution (which it doesn't):
```Dockerfile
# Here: user's Dockerfile content
ENV PREVIOUS_USER=$(id -u -n)
# Here: features installation
USER ${PREVIOUS_USER}
```

The current fix covers a few cases by looking at the Dockerfile (which is hard to cover all cases including variables and multiple stages).
