### ISSUE TITLE
Reverted! thanks for the advice

### ISSUE THREAD

**Issue by mtrackeros** [devcontainers/cli#786]
Reverted! thanks for the advice

_Originally posted by @prulloac in https://github.com/devcontainers/cli/pull/774#discussion_r1532358300_

**Comment by mtrackeros** [comment]
[publish-dev-containers.yml.txt](https://github.com/devcontainers/cli/files/14733243/publish-dev-containers.yml.txt)

**Comment by mtrackeros** [comment]
Reverted! thanks for the advice

**Comment by mtrackeros** [comment]
[publish-dev-containers.yml.txt](https://github.com/devcontainers/cli/files/14733245/publish-dev-containers.yml.txt)

**Comment by mtrackeros** [comment]
[publish-dev-containers.yml.txt](https://github.com/devcontainers/cli/files/14733246/publish-dev-containers.yml.txt)
[publish-dev-containers.yml (1).txt](https://github.com/devcontainers/cli/files/14733250/publish-dev-containers.yml.1.txt)

**Comment by mtrackeros** [comment]
[](url)

**Comment by mtrackeros** [comment]
[publish-dev-containers.yml.1 (1).txt](https://github.com/devcontainers/cli/files/14733256/publish-dev-containers.yml.1.1.txt)

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
