### ISSUE TITLE
Question: How do I find a template ID for the `devcontainer templates apply` command?

### ISSUE THREAD

**Issue by mikoto2000** [devcontainers/cli#792]
How do I find a template ID for the `devcontainer templates apply` command?

I checked https://containers.dev/templates but I can not find a template ID.

**Comment by chrmarti** [comment]
The template's short id is in its `devcontainer-template.json` (e.g., `anaconda-postgres`) which you can find by following the link to the template in the https://containers.dev/templates list. That then needs to be qualified with where the template is published (e.g., `ghcr.io/devcontainers/templates/anaconda-postgres`).

I guess we could add a column with the full id in the table at https://containers.dev/templates. Could you tell us in what context you are going to use it? For scripting? Thanks.

/cc @bamurtaugh

**Comment by mikoto2000** [comment]
@chrmarti 
Thank you for your comment!

> Could you tell us in what context you are going to use it? For scripting?

I'm working on setting up a Go language project and realized I needed a `devcontainer.json`.

Instead of starting from scratch, I looked for a template.

That's when I discovered the  [Available Dev Container Templates Page](https://containers.dev/templates) and `devcontainer templates apply` command, which automatically generates a `devcontainer.json` file.

I decided to use this command to create the initial file and then make necessary modifications to finalize the configuration.

This approach led me to the current issue.
(I can not find template id for apply subcommand...)


> That then needs to be qualified with where the template is published 

I checked https://github.com/devcontainers/templates/tree/main/src/go. but I can not find publishing registry place...

**Comment by bamurtaugh** [comment]
Thanks for opening this!

> I checked https://github.com/devcontainers/templates/tree/main/src/go. but I can not find publishing registry place...

Any of the spec maintainer-driven Templates will be published at a URL like @chrmarti mentioned: `ghcr.io/devcontainers/templates/<id>`, so in this case, it should be `ghcr.io/devcontainers/templates/go`. 

This is an interesting discussion because as I'm poking around https://github.com/devcontainers/templates/pkgs/container/templates%2Fgo and https://github.com/devcontainers/templates/blob/main/src/go/devcontainer-template.json, I don't readily see where this ghcr.io URL is listed for users to discover - @chrmarti am I just missing it?

***

Regarding updating https://containers.dev/templates: a fast initial solution could be adding a note to the top of the available Templates page with the guidance @chrmarti shared here, if folks think that would be helpful. We'd definitely welcome any community PRs to https://github.com/devcontainers/devcontainers.github.io to add this note or any other info you'd find helpful!

**Comment by mikoto2000** [comment]
@bamurtaugh @chrmarti 
Thank you for comment and reply.

> The devcontainers action publishing the template must use ghcr.io by default and use the full repository name devcontainers/template as the path prefix for publishing.

OK. I use `ghcr.io/devcontainers/templates/<id>`.


> @mikoto2000 Noticed it was never mentioned, so just in case this helps: If you don't need to automate it, you can use the Dev Container extension for VS Code to add a devcontainer.json. Its F1 > Dev Containers: Add Dev Container Configuration Files... command lets you pick from the same lists as https://containers.dev/templates and https://containers.dev/features are showing.

Thank you for the information. Since I almost never use VSCode, I wanted to create the template solely through command line operations with devcontainer/cli, without using VSCode.

Therefore, I would appreciate it if the 'https://containers.dev/templates' page could include an ID column, similar to the one on the 'https://containers.dev/features' page.

**Comment by joshspicer** [comment]
> The devcontainers action publishing the template must use ghcr.io by default and use the full repository name devcontainers/template as the path prefix for publishing. /cc @joshspicer in case I'm missing something

That's correct, this _is_ configurable in the [action](https://github.com/devcontainers/action/blob/main/action.yml), although the default values will assume `ghcr.io` and the `owner/repo` to be the "namespace" of the Feature/Template.  

These is the relevant lines of code in the `devcontainers/action` action https://github.com/devcontainers/action/blob/85693cddf23e12779168aead7403ab84642a4b9a/src/main.ts#L42

If not pushing to `ghcr.io`, you'd want to make sure you run a task beforehand in the workflow to login to the relevant container registry

**Comment by joshspicer** [comment]
I like the idea of adding a column to the Templates page with the 'reference', just like we do for [Features](https://containers.dev/features).  We should already have all the needed information available in the index file.

**Comment by mikoto2000** [comment]
I see that `devcontainer-index.json` contains `id` and `version`.

I will use those to create a pull request to add `Reference` and `Latest Version` columns to `Available Templates` page.

**Comment by mikoto2000** [comment]
Thank you.
It is now possible to check the ID on the Available Templates page.
I close this issue.
