### ISSUE TITLE
Should `devcontainers/cli` uses `docker compose` always instead `docker-compose`?

### ISSUE THREAD

**Issue by duduribeiro** [devcontainers/cli#826]
Hey devcontainers/cli folks 👋 

I have a CI that uses `devcontainers/ci` action (which uses the devcontainers/cli) to validate a devcontainer generated for the project.

I'm trying to add the top-level name property into the compose file https://github.com/rails/rails/pull/51791

but it is failing on CI with the error of:
```
he Compose file .. is invalid because:
  'name' does not match any of the regexes: '^x-'
```
https://github.com/rails/rails/actions/runs/9044514158/job/24853256908?pr=51791

I also tried to specify the version 3.8 on the compose but without success. 

I see that `devcontainers/cli` code base uses `docker-compose` instead `docker compose`. should we replace the codebase to use `docker compose` instead so we avoid to use the old compose which is deprecate since jul 23? https://docs.docker.com/compose/migrate/

I also see a test on devcontainers/cli codebase https://github.com/devcontainers/cli/blob/main/src/test/configs/compose-with-name/.devcontainer/docker-compose.yml which tests the exact same scenario but in my case it is not working.

thoughts?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Looking at 👇 , I think the request makes sense for the CLI to switch to the newer Docker compose V2 syntax  (ie `docker compose`) given https://docs.docker.com/compose/migrate/

https://github.com/devcontainers/cli/blob/be1f2034e10395f42843ebf26600a42e11e66531/src/spec-node/devContainers.ts#L161

@gauravsaini04 Can you help take a look at this request? Thanks! 

// cc @chrmarti Let us know if there are any concerns, thanks!

**Comment by chrmarti** [comment]
Sounds good! We currently check for `docker-compose` and if that doesn't exist we use `docker compose`. To minimize breakage, we could turn this around. Similar code exists in the Dev Containers extension which will also need updating to stay consistent.

The check is here: https://github.com/devcontainers/cli/blob/be1f2034e10395f42843ebf26600a42e11e66531/src/spec-node/dockerCompose.ts#L687

**Comment by gauravsaini04** [comment]
pr [#848](https://github.com/devcontainers/cli/pull/848) was merged to the codebase. closing the issue.
