### ISSUE TITLE
devcontainer executable permissions.

### ISSUE THREAD

**Issue by jimsynz** [devcontainers/cli#83]
Hey folks.

Thanks for this - it's awesome!

I followed the instructions and enabled the devcontainer cli both on my Mac and on my Pop_OS linux machine.  On both of these the devcontainer script was correctly symlinked into place, however calling `devcontainer` from a shell caused a permission denied error.  Upon further inspection the `ms-vscode-remote.remote-containers/cli-bin/devcontainer` script was installed with `644` file permissions.  I had to change them to `755` to be able to run it. Sadly, this means that I am getting an error about a corrupt vscode installation.

**Comment by chrmarti** [comment]
@bpasero Sorry, missed that detail:
```ts
		vscode.workspace.fs.copy(
			vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'test-src.sh'),
			vscode.Uri.joinPath(context.globalStorageUri, 'test-dst.sh'),
		);
```

This drops the executable permission. Copying within the workspace folder preserves them.

The actual production code copies from `context.extensionUri` (not the workspace folder).

**Comment by bpasero** [comment]
Under the hood we leverage node.js `fs.copy` method but we also have code to `chmod` after `copy`:

https://github.com/microsoft/vscode/blob/d17e30f8b4c315e72f6c3bb537fd7822a25c8001/src/vs/base/node/pfs.ts#L592

Last change in this area was around 1-2y ago, I think to preserve symlinks. 

@jrieken when using `vscode.workspace.fs` we still go to the renderer process right? Do you recall any recent changes in this area that could explain why `copy` looses executable permissions?

Btw it could well be that this never worked, I am not entirely sure this is a regression.

**Comment by jrieken** [comment]
> @jrieken when using vscode.workspace.fs we still go to the renderer process right? 

It depends. When the file system is contributed by an extension (e.g. not the renderer, not the REH manager) than we short-circuit these request. So, the `file` and `vscode-remote` schemes should always be handled the "usual way" and not go the extension directly

**Comment by chrmarti** [comment]
Not sure when this changed, but the code in Remote-Containers used to work as-is. I will chmod the file after copying as a fix in the extension.

**Comment by chrmarti** [comment]
Available with Remote-Containers 0.243.0-pre-release (switch Remote-Containers to pre-releases from the Extensions viewlet). Thanks.

**Comment by davidpcaldwell** [comment]
See also https://github.com/microsoft/vscode-remote-release/issues/7012. If anyone could help lay out a test case for the fix, I could have a look. (What would I have to remove, basically? If I removed the `Remote - Containers` extension, and then reinstalled it, would that constitute a valid test case?)

**Comment by davidpcaldwell** [comment]
And for what it's worth, this was a regression. Just in case it helps locate others. It used to work out of the box, and then stopped working. My other report in the comment above contains information about when I think it changed.

**Comment by jimsynz** [comment]
Thanks for the great work!
