### ISSUE TITLE
Adding labels to containers build by devcontainer cli

### ISSUE THREAD

**Issue by Roemer** [devcontainers/cli#837]
I have a case where I need to add some specific metadata to a dev-container image build by the dev-container cli.
would it make sense to add a parameter for this to the devcontainer build command?

My use case is that I want to use dev-container build to build images in the CI for reusability and would need some kind of metadata to identify the content of a built image.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Currently, you can achieve this by adding a [LABEL](https://docs.docker.com/reference/dockerfile/#label) in your Dockerfile or pass it as `build.options` in `.devcontainer.json` (see [eg](https://github.com/devcontainers/cli/blob/635ed8ce3fec6977a960dc1c997a7db00d43a8a6/src/test/configs/dockerfile-with-target/.devcontainer.json#L8))

However, I think it would make sense to add a parameter for this to the `devcontainer build` command. Metadata can be very useful for tracking and managing images, especially in a CI/CD environment.

We can add a `--label` parameter to the `devcontainer build` command that allows users to specify key-value pairs. These pairs could then be added to the image as labels during the build process. In the implementation of the `devcontainer build` command, we would need to parse these labels and pass them to the Docker build command using the `-l` or `--label` option.

**Comment by Roemer** [comment]
Yes, this would be exactly what I need.
Currently, I build a temporary `Dockerfile` which contains the image-tag where I need to add the label and then use `docker build` with that `Dockerfile` and just add the label as command line parameter and tag the image with the same tag. Works but just having the `--label` on the devcontainer cli would be much easier.
In bash this would look like:
`echo "FROM <myImage>" | docker build --label myNewLabel="myLabelValue" -t "<myImage>" -`

**Comment by samruddhikhandale** [comment]
@chrmarti Any concerns with supporting a new `--label` property for the `devcontainer build` commands?

**Comment by chrmarti** [comment]
Makes sense 👍

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
feature added to pass the --label to devcontainer cli. Created PR #846 
Kindly review and approve the same. Thank you
