### ISSUE TITLE
OpenTelemetry tracing

### ISSUE THREAD

**Issue by spuliaiev-sfdc** [devcontainers/cli#861]
Hi,

as part of our services we are using devcontainer-cli to start the docker container.
We want to get a telemetry for the processes running during the 
```shell
npx -y @devcontainers/cli@{devcontainer_version} up
```

As a framework we would like to use @opentelemetry
We need this ASAP so would it be acceptable if we implement this and provide it as contribution to this project instead of maintaining our own fork?

**Comment by spuliaiev-sfdc** [comment]
https://github.com/devcontainers/spec/issues/478

**Comment by samruddhikhandale** [comment]
Discussing in https://github.com/devcontainers/spec/issues/478 
Thanks!

**Comment by Deuces9ers** [comment]
And In return??? All files and repos of this self custody code with specified parts shared is no longer the guinea pig. UNDER THE ADVICE OF MY ATTORNEY.  If ya don't want to at least compensate the effort and time then I'll shut this whole thing down. Sick of you all robbing so many s work

**Comment by Deuces9ers** [comment]
> Hi,
> 
> as part of our services we are using devcontainer-cli to start the docker container.
> We want to get a telemetry for the processes running during the 
> ```shell
> npx -y @devcontainers/cli@{devcontainer_version} up
> ```
> 
> As a framework we would like to use @opentelemetry
> We need this ASAP so would it be acceptable if we implement this and provide it as contribution to this project instead of maintaining our own fork?

For sure go ahead thanks for asking I need all the real help I can get and will help the cause as much as it deserves as soon as able to

**Comment by chrmarti** [comment]
Continuing there.
