### ISSUE TITLE
.devcontainer Directory

### ISSUE THREAD

**Issue by alberk8** [devcontainers/cli#879]
Is it possible to set the path for devcontainer.json file?.   The project I am [trying to run ](https://github.com/nanoframework/nf-interpreter/tree/main/.devcontainer) have the json file in subdirectory.

**Comment by bamurtaugh** [comment]
Yes, this should be possible as specified in the spec: https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-reference.md?plain=1#L17 (relevant previous issue https://github.com/devcontainers/spec/issues/159 and PR on the VS Code side https://github.com/microsoft/vscode-remote-release/issues/7548).

cc @chrmarti in case I'm missing anything

**Comment by alberk8** [comment]
I tried `devcontainer up --workspaces-folder nf-interpreter/.devcontainer/ESP32`   and it complain that the path `Error: Dev container config (/nf/nf-interpreter/.devcontainer/ESP32/.devcontainer/devcontainer.json) not found.`

**Comment by chrmarti** [comment]
`--workspaces-folder` would point to the folder that is going to be mount into the container. You can use `--config` to provide the path for the devcontainer.json.

**Comment by alberk8** [comment]
> `--workspaces-folder` would point to the folder that is going to be mount into the container. You can use `--config` to provide the path for the devcontainer.json.

Thanks.  It works with the following cli

`devcontainer up --workspaces-folder nf-interpreter/.devcontainer/ESP32 --config nf-interpreter/.devcontainer/ESP32/devcontainer.json`
