### ISSUE TITLE
Devcontainers cli issue resuming docker-compose codespaces

### ISSUE THREAD

**Issue by eljog** [devcontainers/cli#89]
There were reports of failure in resuming docker-compose codespaces, with the following error.
```
2022-06-29 19:30:32.390Z: ERROR: build path /tmp/devcontainers_cli_empty either does not exist, is not accessible, or is not a valid URL.

context: /tmp/devcontainers_cli_empty
```

Codespaces are resumed on a new VM each time and the `tmp` directory contents of the VM on which the container was originally built is not available on the VMs where it is subsequently resumed.
As mentioned on the [original issue](https://github.com/github/codespaces/issues/8834#issuecomment-1183781810), we have applied a temporary fix in Codespaces agent, that will pre-create the `/tmp/devcontainers_cli_empty` on the Codespaces VM before calling the `devcontainers-cli` for starting the containers.

- We might need a more permanent fix implemented in `devcontainers-cli` to ensure this directory is present on the machine before attempting to build/start containers
- Question? Is it safe to put the conents to `/tmp` directory, as different OS' may have different settings as to how it cleans/claims space in tmp

**Comment by chrmarti** [comment]
Moved this path to the persisted folder in https://github.com/devcontainers/cli/commit/bfaba09eb0ebda7ae99d6329ed3435e343009321 which I expect should fix it. Closing, let me know if this is still a problem, thanks.
