### ISSUE TITLE
postCreateCommand of parent image always running

### ISSUE THREAD

**Issue by sevetseh28** [devcontainers/cli#907]
Hi, I have a devcontainer.json which points to an image built with the CLI. That image specifies a `postCreateCommand` that is not relevant in my child devcontianer.json. 

My child `devcontainer.json` specifies a different `postCreateCommand`, however, the CLI seems to be running the parent `postCreateCommand` regardless, which naturally fails for the child. 

I wanted to report this as this might be a common use case to allow child devcontainer.json to disable executing the parent commands.

Thanks!

**Comment by sevetseh28** [comment]
Any ideas? this seems to be aborting the copying of the Git configuration to my devcontianer as well.

**Comment by chrmarti** [comment]
The lifecycle scripts are collected and not overwritten. (Documented in https://github.com/devcontainers/spec/blob/main/docs/specs/image-metadata.md.)

The only way around this is to modify the base image or use a different base image.
