### ISSUE TITLE
The docker run command display on "devcontainer up" differ from the docker run command seen in strace

### ISSUE THREAD

**Issue by hpe-ykoehler** [devcontainers/cli#910]
I have the following scenario, I want to run a jenkins job that will initiate a devcontainer image.  I need for example to use the Jenkins pipeline "docker.image().inside()" in order to integrate my jenkins pipeline with devcontainer.

Since I cannot use the devcontainer CLI to start my container I need to use the equivalent "docker run..."

I try to extract the logic from devcontainer up and found that the display at the end

```
[3346 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/work/krypton/jenkins-agent-image,target=/workspaces/jenkins-agent-image -l devcontainer.local_folder=/work/krypton/jenkins-agent-image -l devcontainer.config_file=/work/krypton/jenkins-agent-image/.devcontainer/devcontainer.json --privileged --entrypoint /bin/sh vsc-jenkins-agent-image-50b5c5a9715e8ac3af6ca2d0f93b30249062d7930045f21fde950743a2176563-uid -c echo Container started
```

Diffes from the version I found in the strace log

```
["docker", "run", "--sig-proxy=false", "-a", "STDOUT", "-a", "STDERR", "--mount", "type=bind,source=/work/krypton/jenkins-agent-image,target=/workspaces/jenkins-agent-image", "-l", "devcontainer.local_folder=/work/krypton/jenkins-agent-image", "-l", "devcontainer.config_file=/work/krypton/jenkins-agent-image/.devcontainer/devcontainer.json", "--privileged", "--entrypoint", "/bin/sh", "vsc-jenkins-agent-image-50b5c5a9715e8ac3af6ca2d0f93b30249062d7930045f21fde950743a2176563-uid", "-c", "echo Container started\ntrap \"exit 0\" 15\n/usr/local/share/docker-init.sh\nexec \"$@\"\nwhile sleep 1 & wait $!; do :; done", "-"],
```

See the missing call to /usr/local/share/docker-init.sh in the output of devcontainer.

I believe this may be a missing escape issue where the \n in the arguments is not escaped before being printed.

**Comment by chrmarti** [comment]
The log only shows the first line. It stops at the newline to avoid flooding the log with a single command.
